### ISSUE TITLE
Possible Memory Leak?

### ISSUE THREAD

**Issue by michaeldim1** [N8BWert/rc4-plaintext#3]
I've tried building the program a few times. I am running Windows 10 LTSC 2021.

Upon run I get the following output in the powershell terminal:

`iteration: 0
current key value: 0x000000000084A8ABD534CE7C63`

Which does not update. Meanwhile according to task manager, there is some CPU use and a steadily growing ram use which maxes out my RAM at about 26 GB in about a minute. The first time it crashed my system.

![Taskmgr_Xsw2k1DAGC](https://user-images.githubusercontent.com/55327800/193481888-b28b6de9-70c0-4c9b-8aff-585bc0f5c39d.png)

Specs are as follows:
Intel Core i7 7800X
32.0GB DDR4
ATI Radeon RX 480 Graphics (XFX Pine Group)

**Comment by roysjosh** [comment]
See pull request #2
